org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
neo_version=21.1.234
loader_version_range=[4,)
minecraft_version_range=[1.21.1,1.22)

mod_id=urbanforma_fireworks
mod_name=Urbanforma:Fireworks
mod_license=MIT
mod_version=0.3.1b
mod_group_id=com.urbanforma.fireworks
mod_authors=Dotkk
mod_description=An Urbanforma:neo add-on featuring spectacular fireworks.
