package com.urbanforma.fireworks.content.batch_other_extra;

import java.util.ArrayList;
import java.util.List;

/**
 * Deterministic, client-neutral geometry for the additional Other series.
 *
 * <p>Each route is a finite collection of open three-dimensional tracks. The scheduler owner may consume one
 * tick of {@link #samplesAtTick(BatchOtherExtraFirework.TrajectoryContract, long, int)}; this class owns neither a
 * queue nor a particle object. Seeded phase offsets are derived with fixed integer mixing and never consult a
 * clock or mutable source.</p>
 */
public final class BatchOtherExtraTrajectory {
    public static final int MAX_PER_TICK = BatchOtherExtraFirework.MAX_PER_TICK;
    public static final int MAX_OWNED_PARTICLES = BatchOtherExtraFirework.MAX_OWNED_PARTICLES;
    private static final double TWO_PI = Math.PI * 2.0D;
    private static final double SQRT_THREE = 1.7320508075688772D;
    private static final long PHASE_SALT = 0x9E3779B97F4A7C15L;
    private static final long TWIST_SALT = 0xD6E8FEB86659FD93L;

    private BatchOtherExtraTrajectory() {
    }

    public enum Layer {
        CORE,
        PRIMARY,
        SECONDARY,
        ACCENT
    }

    public record Point(double x, double y, double z) {
        public Point {
            if (!Double.isFinite(x) || !Double.isFinite(y) || !Double.isFinite(z)) {
                throw new IllegalArgumentException("Extra Other trajectory point must be finite");
            }
        }

        public Point add(Point other) {
            return new Point(this.x + other.x, this.y + other.y, this.z + other.z);
        }

        public Point scale(double factor) {
            return new Point(this.x * factor, this.y * factor, this.z * factor);
        }
    }

    public record Sample(
            int tick,
            int component,
            int branch,
            int segment,
            Layer layer,
            Point point,
            int lifetimeTicks,
            int trailLength,
            int colorStage) {
        public Sample {
            if (tick < 0 || component < 0 || branch < 0 || segment < 0 || layer == null || point == null
                    || lifetimeTicks <= 0 || trailLength < 0 || colorStage < 0 || colorStage > 2) {
                throw new IllegalArgumentException("Invalid Extra Other trajectory sample");
            }
        }
    }

    /** Returns the exact finite emission count implied by the contract. */
    public static int plannedParticles(BatchOtherExtraFirework.TrajectoryContract contract) {
        int total = 0;
        for (int tick = contract.startDelayTicks();
                tick < contract.startDelayTicks() + contract.segmentCount();
                tick++) {
            total = Math.addExact(total, samplesAtTick(contract, 0L, tick).size());
            if (total > MAX_OWNED_PARTICLES) {
                throw new IllegalArgumentException("Extra Other trajectory exceeds owned particle bound");
            }
        }
        return total;
    }

    /** Returns the exact largest one-tick list generated by the finite schedule. */
    public static int maximumParticlesPerTick(BatchOtherExtraFirework.TrajectoryContract contract) {
        int maximum = 0;
        for (int tick = contract.startDelayTicks();
                tick < contract.startDelayTicks() + contract.segmentCount();
                tick++) {
            maximum = Math.max(maximum, samplesAtTick(contract, 0L, tick).size());
        }
        if (maximum <= 0 || maximum > MAX_PER_TICK) {
            throw new IllegalArgumentException("Extra Other trajectory exceeds per-tick particle bound");
        }
        return maximum;
    }

    /**
     * Samples one finite tick. The capacity is derived from the hard component/branch caps and is checked before
     * returning, so this method cannot grow a shared queue or an unbounded collection.
     */
    public static List<Sample> samplesAtTick(
            BatchOtherExtraFirework.TrajectoryContract contract,
            long seed,
            int tick) {
        int segment = tick - contract.startDelayTicks();
        if (segment < 0 || segment >= contract.segmentCount()) {
            return List.of();
        }
        ArrayList<Sample> samples = new ArrayList<>(Math.min(
                MAX_PER_TICK,
                contract.branchCount() * contract.componentCount()));
        for (int component = 0; component < contract.componentCount(); component++) {
            if (!componentIsActive(contract, component, segment)) {
                continue;
            }
            for (int branch = 0; branch < contract.branchCount(); branch++) {
                if (!branchIsActive(contract, component, branch, segment)) {
                    continue;
                }
                Point point = sample(contract, seed, component, branch, segment);
                samples.add(new Sample(
                        tick,
                        component,
                        branch,
                        segment,
                        layer(contract, component, branch, segment),
                        point,
                        lifetime(contract, component, branch, segment),
                        trailLength(contract, component, branch, segment),
                        colorStage(contract, component, branch, segment)));
                if (samples.size() > MAX_PER_TICK) {
                    throw new IllegalArgumentException("Extra Other trajectory emitted more than 720 particles in one tick");
                }
            }
        }
        return List.copyOf(samples);
    }

    /** Returns one validated point for a caller that needs a deterministic geometry probe. */
    public static Point samplePoint(
            BatchOtherExtraFirework.TrajectoryContract contract,
            long seed,
            int component,
            int branch,
            int segment) {
        if (component < 0 || component >= contract.componentCount()
                || branch < 0 || branch >= contract.branchCount()
                || segment < 0 || segment >= contract.segmentCount()) {
            throw new IllegalArgumentException("Extra Other sample index is outside the trajectory contract");
        }
        return sample(contract, seed, component, branch, segment);
    }

    /** Conservative finite envelope estimate including one tick of trail padding. */
    public static int conservativeEnvelopeBlocks(BatchOtherExtraFirework.TrajectoryContract contract) {
        double coordinateSpan = contract.outerRadius() * 2.0D;
        double offsets = (contract.verticalAmplitude() + contract.lateralAmplitude() + contract.depthAmplitude()) * 2.0D;
        double routeAllowance = switch (contract.route()) {
            case AXIS_WEAVE, TRIAD_STEP -> 8.0D;
            case TETRA_TWIST, COUNTER_TWIST_BRAID, TRIPLE_TORSION, PHASED_SPINDLE -> 10.0D;
            case POLAR_STAIRCASE, PRISM_RETURN, OCTANT_GAP, CANTED_COLUMNS, DIAGONAL_LADDER,
                    SPLIT_MERGE, CUBIC_OFFSET, VERTICAL_FRACTURE -> 12.0D;
            case AXIAL_TUNNEL -> 14.0D;
        };
        return (int) Math.ceil(coordinateSpan + offsets + routeAllowance);
    }

    private static boolean componentIsActive(
            BatchOtherExtraFirework.TrajectoryContract contract,
            int component,
            int segment) {
        int cadence = segment + contract.phaseOffset() + component * contract.componentPhaseStride();
        if (Math.floorMod(cadence, contract.pulseStride()) != 0) {
            return false;
        }
        return switch (contract.route()) {
            case AXIS_WEAVE, TETRA_TWIST, COUNTER_TWIST_BRAID, AXIAL_TUNNEL, SPLIT_MERGE, PHASED_SPINDLE -> true;
            case TRIAD_STEP -> segment % 6 != 5 || component == 1;
            case POLAR_STAIRCASE -> segment % 8 != 7 || component == 0;
            case PRISM_RETURN -> segment < contract.segmentCount() - 2 || component == 0;
            case OCTANT_GAP -> component != 3 || segment % 4 != 2;
            case CANTED_COLUMNS -> segment % 5 != 4 || component == 2;
            case DIAGONAL_LADDER -> segment % 3 != 2 || component == 0;
            case TRIPLE_TORSION -> segment % 7 != 6 || component == 2;
            case CUBIC_OFFSET -> segment % 4 != 3 || component == 1;
            case VERTICAL_FRACTURE -> segment % 6 != 4 || component == 0;
        };
    }

    private static boolean branchIsActive(
            BatchOtherExtraFirework.TrajectoryContract contract,
            int component,
            int branch,
            int segment) {
        return switch (contract.route()) {
            case OCTANT_GAP -> Math.floorMod(branch + component + segment, 5) != 4;
            case DIAGONAL_LADDER -> Math.floorMod(branch + segment * 2 + component, 7) != 6;
            case VERTICAL_FRACTURE -> Math.floorMod(branch + component * 2 + segment, 6) != 5;
            case CUBIC_OFFSET -> Math.floorMod(branch + component + segment, 8) != 7;
            default -> true;
        };
    }

    private static Point sample(
            BatchOtherExtraFirework.TrajectoryContract contract,
            long seed,
            int component,
            int branch,
            int segment) {
        double progress = (segment + 1.0D) / contract.segmentCount();
        double eased = progress * progress * (3.0D - 2.0D * progress);
        double phase = TWO_PI * branch / contract.branchCount()
                + seededAngle(seed, contract.route().ordinal(), branch);
        double radius = contract.innerRadius() + (contract.outerRadius() - contract.innerRadius()) * eased;
        return switch (contract.route()) {
            case AXIS_WEAVE -> axisWeave(contract, phase, radius, component, branch, segment, progress);
            case TRIAD_STEP -> triadStep(contract, phase, radius, component, branch, segment, progress);
            case TETRA_TWIST -> tetraTwist(contract, phase, radius, component, branch, segment, progress);
            case POLAR_STAIRCASE -> polarStaircase(contract, phase, radius, component, branch, segment, progress);
            case PRISM_RETURN -> prismReturn(contract, phase, radius, component, branch, segment, progress);
            case COUNTER_TWIST_BRAID -> counterTwistBraid(contract, phase, radius, component, branch, segment, progress);
            case OCTANT_GAP -> octantGap(contract, phase, radius, component, branch, segment, progress);
            case CANTED_COLUMNS -> cantedColumns(contract, phase, radius, component, branch, segment, progress);
            case AXIAL_TUNNEL -> axialTunnel(contract, phase, radius, component, branch, segment, progress);
            case DIAGONAL_LADDER -> diagonalLadder(contract, phase, radius, component, branch, segment, progress);
            case TRIPLE_TORSION -> tripleTorsion(contract, phase, radius, component, branch, segment, progress);
            case SPLIT_MERGE -> splitMerge(contract, phase, radius, component, branch, segment, progress);
            case CUBIC_OFFSET -> cubicOffset(contract, phase, radius, component, branch, segment, progress);
            case VERTICAL_FRACTURE -> verticalFracture(contract, phase, radius, component, branch, segment, progress);
            case PHASED_SPINDLE -> phasedSpindle(contract, phase, radius, component, branch, segment, progress);
        };
    }

    private static Point axisWeave(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double sign = ((branch + component) & 1) == 0 ? 1.0D : -1.0D;
        double weavePhase = phase * 2.0D + progress * Math.PI * 3.0D + component;
        double transverse = Math.sin(weavePhase) * c.lateralAmplitude() * (0.35D + 0.65D * progress);
        double depth = Math.cos(weavePhase * 0.73D) * c.depthAmplitude();
        double along = sign * radius;
        return switch (component) {
            case 0 -> new Point(along, transverse, depth);
            case 1 -> new Point(transverse, along, depth);
            default -> new Point(transverse, depth, along);
        };
    }

    private static Point triadStep(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double step = Math.floor(progress * 7.0D) / 7.0D;
        double angle = phase + component * TWO_PI / 3.0D + c.twist() * step;
        double radial = radius * (0.42D + 0.58D * step);
        double lift = ((component & 1) == 0 ? 1.0D : -1.0D)
                * c.verticalAmplitude() * (0.2D + step)
                + Math.sin(progress * Math.PI * 4.0D + phase) * c.depthAmplitude() * 0.55D;
        double cross = Math.cos(phase * 1.7D + segment * 0.41D) * c.lateralAmplitude();
        return new Point(
                Math.cos(angle) * radial + cross * Math.sin(angle),
                lift,
                Math.sin(angle) * radial + cross * Math.cos(angle));
    }

    private static Point tetraTwist(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        int[][] signs = {{1, 1, 1}, {1, -1, -1}, {-1, 1, -1}, {-1, -1, 1}};
        int[] direction = signs[component];
        double bx = direction[0] / SQRT_THREE;
        double by = direction[1] / SQRT_THREE;
        double bz = direction[2] / SQRT_THREE;
        double ux = 1.0D / SQRT_THREE;
        double uy = -1.0D / SQRT_THREE;
        double uz = 0.0D;
        double vx = by * uz - bz * uy;
        double vy = bz * ux - bx * uz;
        double vz = bx * uy - by * ux;
        double twist = phase + c.twist() * progress + component * 0.31D;
        double offset = c.lateralAmplitude() * Math.sin(twist) * (0.35D + progress * 0.65D);
        double depth = c.depthAmplitude() * Math.cos(twist * 0.77D);
        return new Point(
                bx * radius + ux * offset + vx * depth,
                by * radius + uy * offset + vy * depth,
                bz * radius + uz * offset + vz * depth);
    }

    private static Point polarStaircase(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double stair = Math.floor(progress * 8.0D) / 8.0D;
        double angle = phase + component * Math.PI + c.twist() * stair;
        double sweep = c.lateralAmplitude() + radius * 0.34D;
        double vertical = (component == 0 ? 1.0D : -1.0D) * radius * 0.86D
                + Math.sin(progress * Math.PI * 2.0D + phase) * c.verticalAmplitude();
        return new Point(Math.cos(angle) * sweep, vertical, Math.sin(angle) * sweep);
    }

    private static Point prismReturn(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double reach = progress < 0.64D
                ? progress / 0.64D
                : Math.max(0.0D, 1.0D - (progress - 0.64D) / 0.36D);
        double angle = phase + component * TWO_PI / 3.0D;
        double radial = radius * (0.25D + 0.75D * reach);
        double y = ((segment / 4) & 1) == 0 ? c.verticalAmplitude() : -c.verticalAmplitude();
        y += Math.sin(progress * Math.PI * 6.0D + phase) * c.depthAmplitude();
        return new Point(Math.cos(angle) * radial, y, Math.sin(angle) * radial);
    }

    private static Point counterTwistBraid(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double direction = component == 0 ? 1.0D : -1.0D;
        double angle = phase + direction * c.twist() * progress + component * Math.PI;
        double braid = Math.sin(progress * Math.PI * 4.0D + phase) * c.lateralAmplitude() * 0.65D;
        double z = ((branch & 1) == 0 ? 1.0D : -1.0D) * radius * 0.72D
                + Math.cos(progress * Math.PI * 3.0D + phase) * c.depthAmplitude();
        return new Point(
                Math.cos(angle) * (radius * 0.72D) + braid,
                Math.sin(angle) * (radius * 0.72D) - braid,
                z);
    }

    private static Point octantGap(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        int octant = Math.floorMod(branch + component * 2, 8);
        double sx = (octant & 1) == 0 ? 1.0D : -1.0D;
        double sy = (octant & 2) == 0 ? 1.0D : -1.0D;
        double sz = (octant & 4) == 0 ? 1.0D : -1.0D;
        double diagonal = radius / SQRT_THREE;
        double offset = Math.sin(progress * Math.PI * 5.0D + phase) * c.lateralAmplitude() * 0.45D;
        return new Point(
                sx * diagonal + offset * sy,
                sy * diagonal + Math.cos(phase + segment * 0.27D) * c.verticalAmplitude() * 0.35D,
                sz * diagonal + offset * sx);
    }

    private static Point cantedColumns(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double columnAngle = component * TWO_PI / 3.0D;
        double base = radius * 0.48D;
        double lean = (progress - 0.5D) * c.lateralAmplitude();
        double y = (progress * 2.0D - 1.0D) * radius * 0.95D
                + Math.sin(phase * 1.4D + progress * Math.PI * 2.0D) * c.verticalAmplitude() * 0.45D;
        double crossbar = segment % 5 == 0 ? c.depthAmplitude() : 0.0D;
        return new Point(
                Math.cos(columnAngle) * base + lean + crossbar * Math.sin(columnAngle),
                y,
                Math.sin(columnAngle) * base + lean + crossbar * Math.cos(columnAngle));
    }

    private static Point axialTunnel(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double angle = phase + component * Math.PI * 0.5D + c.twist() * progress;
        double ellipse = component == 2 ? 0.42D : 0.76D;
        double x = Math.cos(angle) * (c.lateralAmplitude() + radius * ellipse * 0.28D);
        double y = Math.sin(angle) * (c.verticalAmplitude() + radius * ellipse * 0.22D);
        double z = ((branch + component) & 1) == 0 ? radius * 1.34D : -radius * 1.34D;
        z += Math.sin(progress * Math.PI * 5.0D + phase) * c.depthAmplitude();
        return new Point(x, y, z);
    }

    private static Point diagonalLadder(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double diagonal = (progress * 2.0D - 1.0D) * radius;
        double rung = (segment % 4 == 0 ? 1.0D : -1.0D) * c.lateralAmplitude() * (0.35D + progress * 0.65D);
        double tilt = component == 0 ? 1.0D : -1.0D;
        double x = diagonal + tilt * rung;
        double z = diagonal * 0.62D - tilt * rung * 0.8D;
        double y = Math.sin(phase + progress * Math.PI * 3.0D) * c.verticalAmplitude() + component * c.depthAmplitude();
        return new Point(x, y, z);
    }

    private static Point tripleTorsion(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double direction = (component & 1) == 0 ? 1.0D : -1.0D;
        double angle = phase + component * TWO_PI / 3.0D + direction * c.twist() * progress;
        double breathing = 0.62D + 0.38D * Math.sin(progress * Math.PI * 3.0D + component);
        double radial = radius * breathing;
        return new Point(
                Math.cos(angle) * radial,
                Math.sin(angle) * radial + Math.sin(phase + progress * Math.PI * 5.0D) * c.verticalAmplitude(),
                (progress * 2.0D - 1.0D) * c.depthAmplitude() * 1.9D
                        + Math.cos(angle * 0.7D) * radius * 0.52D);
    }

    private static Point splitMerge(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double separation = Math.sin(progress * Math.PI) * c.lateralAmplitude();
        double lobe = component == 0 ? 1.0D : -1.0D;
        double forward = (progress * 2.0D - 1.0D) * radius;
        double cross = Math.cos(phase + progress * Math.PI * 4.0D) * c.depthAmplitude();
        return new Point(
                forward,
                lobe * separation + Math.sin(phase) * c.verticalAmplitude() * 0.55D,
                cross + lobe * radius * 0.34D);
    }

    private static Point cubicOffset(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        int edgeAxis = Math.floorMod(segment / 4 + component, 3);
        double sign = ((branch + segment + component) & 1) == 0 ? 1.0D : -1.0D;
        double edge = sign * (progress * 2.0D - 1.0D) * radius;
        double offsetA = (component - 1) * c.lateralAmplitude();
        double offsetB = Math.sin(phase + segment * 0.5D) * c.depthAmplitude();
        return switch (edgeAxis) {
            case 0 -> new Point(edge, offsetA, offsetB);
            case 1 -> new Point(offsetA, edge, offsetB);
            default -> new Point(offsetA, offsetB, edge);
        };
    }

    private static Point verticalFracture(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double fracture = ((segment % 6) - 2.5D) * c.depthAmplitude() * 0.28D;
        double angle = phase + component * Math.PI * 0.5D;
        double y = (progress * 2.0D - 1.0D) * radius * 1.18D
                + Math.sin(progress * Math.PI * 6.0D + phase) * c.verticalAmplitude();
        double radial = radius * (0.28D + 0.42D * Math.sin(progress * Math.PI));
        return new Point(
                Math.cos(angle) * radial + fracture,
                y,
                Math.sin(angle) * radial - fracture);
    }

    private static Point phasedSpindle(
            BatchOtherExtraFirework.TrajectoryContract c,
            double phase,
            double radius,
            int component,
            int branch,
            int segment,
            double progress) {
        double spindle = Math.sin(Math.PI * progress);
        double angle = phase + component * TWO_PI / 3.0D + c.twist() * (progress - 0.5D);
        double width = c.lateralAmplitude() * (0.32D + 0.68D * spindle) + radius * 0.2D * spindle;
        double length = (progress * 2.0D - 1.0D) * radius * 1.16D;
        return new Point(
                Math.cos(angle) * width,
                Math.sin(angle) * width + component * c.verticalAmplitude() * 0.35D,
                length + Math.cos(angle * 0.6D) * c.depthAmplitude());
    }

    private static Layer layer(
            BatchOtherExtraFirework.TrajectoryContract contract,
            int component,
            int branch,
            int segment) {
        if (segment == 0 || (component == 0 && segment % 9 == 0)) {
            return Layer.CORE;
        }
        return switch (Math.floorMod(component + segment + contract.route().ordinal(), 3)) {
            case 0 -> Layer.PRIMARY;
            case 1 -> Layer.SECONDARY;
            default -> Layer.ACCENT;
        };
    }

    private static int lifetime(
            BatchOtherExtraFirework.TrajectoryContract contract,
            int component,
            int branch,
            int segment) {
        return contract.baseLifetimeTicks()
                + Math.floorMod(branch + component * 3 + segment, contract.lifetimeSpreadTicks());
    }

    private static int trailLength(
            BatchOtherExtraFirework.TrajectoryContract contract,
            int component,
            int branch,
            int segment) {
        return contract.baseTrailLength()
                + Math.floorMod(branch + segment + component, contract.trailSpread() + 1);
    }

    private static int colorStage(
            BatchOtherExtraFirework.TrajectoryContract contract,
            int component,
            int branch,
            int segment) {
        return Math.floorMod(component + segment / Math.max(1, contract.pulseStride()), 3);
    }

    private static double seededAngle(long seed, int routeOrdinal, int branch) {
        long mixed = mix(seed ^ PHASE_SALT ^ ((long) routeOrdinal * TWIST_SALT) ^ ((long) branch * PHASE_SALT));
        return (((mixed >>> 16) & 0xFFFFL) / 65_536.0D - 0.5D) * 0.28D;
    }

    private static long mix(long value) {
        long mixed = value;
        mixed ^= mixed >>> 30;
        mixed *= 0xBF58476D1CE4E5B9L;
        mixed ^= mixed >>> 27;
        mixed *= 0x94D049BB133111EBL;
        return mixed ^ (mixed >>> 31);
    }
}
